### ISSUE TITLE
CostBuffers: qué hacer con los convex hulls menores a 100, 200...800km²

### ISSUE THREAD

**Issue by indradecastro** [neckera/Scales-riberas-R#6]
@Senta16, he hecho una descripción del problema para q quede constancia y lo resolvamos en otro momento. Hay un par de problemillas minusculos más (otros issues). Deberíamos recordarlos en el futuro (al menos para el paper).

1. Las áreas de las Basins están constreñidas a q sean mayores a 100, 200...800km² en cada escala.
2. Las áreas de los GeoBuffers tienen idénticas medianas a las áreas de las Basins para cada escala.
3. ¿las medianas de las áreas de los CostBuffers deben ser similares a las medianas de las áreas de las Basins y GeoBuffers?

**Criterios seguidos para el método CostBuffers:**
Un pool es un conjunto de inventarios a distancia de coste menor a cierto umbral desde un inventario central.
A la hora de calcular las áreas de los pools,
Se dibujan convex hulls q engloban los inventarios de cada pool.
Las áreas de estos convex hulls deberían ser comparables a las áreas de las Basins y de los GeoBuffers (es decir, las medianas a cada escala).

**Problema:**
Se pueden calcular convex hulls con medianas muy parecidas (con precisión de 100km² aprox.),
PERO surgen muchos convex hulls de área menor a 100, 200...800km² en cada escala.

**Preguntas:**
¿se deben eliminar los convex hulls menores a 100,200...800km² ? y q las medianas SIGAN siendo similares a las de Basins y GeoBuffers?

**Comment by indradecastro** [comment]
Hay varios convex hulls por debajo del área mínima para cada escala (100:800 km²)
> sapply(seq_along(area.cos), function(scale){length(which(area.cos[[scale]]<(scale*100)))})
[1] 14  9  6 10 12  9  6  4

pero la mayoría son NAs, es decir ni siquiera se pudo CONSTRUIR el convex hull.

> sapply(area.cos, function(scale){length(which(is.na(scale)))})
scale.1 scale.2 scale.3 scale.4 scale.5 scale.6 scale.7 scale.8 
     10       6       4       2       1       1       1       0 

Hay varias razones q pueden impedir la construcción de un convex hull:

- falta de inventarios (inventarios < 3, produce una linea, no un polígono)
- 3 o más inventarios, pero con coordenadas solapadas (funcionan como menos de 3 puntos)

Esto ocurre sobretodo en las escalas pequeñas.
No así en las grandes, donde se aprecia q no hay muchas áreas = NA.
En estos casos simplemente la orografía o el aislamiento supone unos costes muy elevados para integrar nuevos inventarios y el convex hull queda con un área menor al límite de la escala.

**Comment by neckera** [comment]
Los convex hulls en escalas grandes está bien, es algo razonable yo creo por lo que cuentas. En el caso de las peques... Bueno, tenemos que decidir que hacemos con esas vegas y segundas bandas, entonces. ¿Está ya puesta la reu?

**Comment by indradecastro** [comment]
Resumiendo:
Los ConvexHulls deben cumplir 2 criterios:

1. min(area costbuffers) > 100:800 km²
2. median(area costbuffers) = median(area basins)

Se ha corregido el código para cumplir ambos criterios:
1. > sapply(area.cos, min, na.rm=T)
121.0072  211.4701  306.8200  449.8006  502.8709  672.8773  758.4206 1117.7875

2. > sapply(area.bas, median)
 scale.1  scale.2  scale.3  scale.4  scale.5  scale.6  scale.7  scale.8 
1337.337 2310.140 3227.133 4692.981 5848.847 7263.477 7943.401 8338.382 
sapply(area.cos, median, na.rm=T)
1324.839 1917.342 2543.497 3381.233 4401.992 5804.680 6867.800 8309.366

Esto resulta en pérdida de costbuffers útiles:
> sapply(area.cos, function(scale){paste(round(length(which(is.na(scale)))/662*100,2), "%")})
3.93%   2.72%   1.51%   1.81%   1.96%   1.51%   1.21%   0.6%

Lo dejaré reflejado en la evaluación de resultados.
