### ISSUE TITLE
Evaluar sistemáticamente los resultados

### ISSUE THREAD

**Issue by indradecastro** [neckera/Scales-riberas-R#7]
@Senta16, sería un gesto de transparencia, honestidad y buena fé mostrar la "completitud" de los resultados q usamos para confeccionar los gráficos.
Se me ocurre q para cada método y cada escala evaluemos:

- **cuántos valores teóricos debería haber?** (662? menos?)
- **cuántos de esos son NAs?** (no hemos conseguido datos para calcularlos)
- **cuántos cumplen con los criterios q establecimos al principio?** (me refiero a las áreas de al menos 100:800km², quizá hubiera más criterios q estoy olvidando...?)

**Comment by neckera** [comment]
@indradecastro, 100% de acuerdo. Creo que sería lo más honesto. Se puede añadir una tablita en material suplementario, cómo lo ves?

**- cuántos valores teóricos debería haber? (662? menos?)** -> 662 para cost y geo, nº basins/scale para las cuencas
**- cuántos de esos son NAs? (no hemos conseguido datos para calcularlos)** -> Supongo que te refieres a los pools (rich y clima), no? Me parece bien
**- cuántos cumplen con los criterios q establecimos al principio? (me refiero a las áreas de al menos 100:800km², quizá hubiera más criterios q estoy olvidando...?)** -> Esto no sé si hace falta porque todos los que no cumplen esos criterios de área nos los cargamos dado que son artefactos, no?

**Comment by indradecastro** [comment]
vale, de acuerdo en todo. a ver qué dice Nagore.
el 3er punto (el criterio de 100:800km²)... los eliminamos para basins, 
pero también aparecen "artefactos" de este tipo en CostBuffers. Son 
ConvexHulls pequeñitos q no llegan al mínimo, pero son muy pocos, ahora 
mismo no recuerdo cuantos, ¿unos 10 de 8*662?. De momento los he dejado 
pq apenas molestan ni a la mediana ni ná.
lo hablamos cuando nos veamos.

**Comment by neckera** [comment]
Quitar artefactos por ser coherente y usar el mismo criterio todo el rato

**Comment by indradecastro** [comment]
Evaluación de resultados completa (incluyendo la eliminación de "artefactos" en CostBuffers, ver issue #6)
